#!/usr/bin/env python3
"""Turn co-writer's session log and the author's edits into a corrections file.

    python capture_edits.py [--repo DIR] [--threshold 0.5] [--recompute]

co-writer appends one entry per rewrite to <repo>/.co-writer/log/*.md (the
format is specified in SKILL.md, "Session log"). Each entry records what was
*delivered*. The paper's .tex file, as the author later committed it, records
what was *accepted*. This script joins the two:

  for every logged output paragraph, find the paragraph in the target file
  that best matches it, and write the word-level diff delivered -> accepted
  together with a normalized edit distance to <repo>/.co-writer/corrections.md.

corrections.md is the training signal for the voice profile: recurring edits
become Never entries, regraded rules, or new specimens (SKILL.md,
"Maintenance"). The summary printed at the end shows mean distance per slot
and per profile version -- a later profile version is better if and only if
the author edits less.

Idempotent: entries already present in corrections.md are skipped unless
--recompute is given. Standard library only.
"""

from __future__ import annotations

import argparse
import collections
from collections.abc import Sequence
import difflib
import pathlib
import re
import sys
from typing import Any

LOG_DIR = ".co-writer/log"
OUT_FILE = ".co-writer/corrections.md"
WORD_RE = re.compile(r"\S+")
_HEADER = (
    "# co-writer corrections\n\nGenerated by scripts/capture_edits.py."
    " delivered -> accepted, word-level: [-removed-] {+added+}.\n\n"
)


# ---------------------------------------------------------------------------
# log parsing
# ---------------------------------------------------------------------------


def find_repo(start: pathlib.Path) -> pathlib.Path | None:
    """Returns the nearest folder at or above start that holds .co-writer/."""
    for folder in [start, *start.parents]:
        if (folder / ".co-writer").is_dir():
            return folder
    return None


def parse_entry(path: pathlib.Path) -> dict[str, Any] | None:
    """Parses one session-log entry.

    Args:
      path: The entry: a frontmatter block, then "## Input", "## Output" and
        "## Note" sections.

    Returns:
      The frontmatter fields, with "id" defaulting to the file's stem, plus
      "_path" and the text of the "input", "output" and "note" sections; or
      None when the file has no frontmatter.
    """
    text = path.read_text(encoding="utf-8", errors="replace")
    match = re.match(r"---\s*\n(.*?)\n---\s*\n", text, flags=re.DOTALL)
    if not match:
        return None
    meta: dict[str, Any] = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip()
    body = text[match.end() :]
    sections = {}
    section = r"^##\s+(\w+)\s*\n(.*?)(?=^##\s+\w+\s*$|\Z)"
    for name, content in re.findall(section, body, flags=re.DOTALL | re.M):
        sections[name.lower()] = content.strip()
    meta.setdefault("id", path.stem)
    meta["_path"] = path
    meta["input"] = sections.get("input", "")
    meta["output"] = sections.get("output", "")
    meta["note"] = sections.get("note", "")
    return meta


def paragraphs(text: str) -> list[str]:
    """Splits text at blank lines into stripped, non-empty paragraphs."""
    return [
        paragraph.strip()
        for paragraph in re.split(r"\n\s*\n", text)
        if paragraph.strip()
    ]


def words(text: str) -> list[str]:
    """Splits text at whitespace."""
    return WORD_RE.findall(text)


# ---------------------------------------------------------------------------
# matching and diffing
# ---------------------------------------------------------------------------


def edit_distance(before: Sequence[str], after: Sequence[str]) -> float:
    """Normalized word-level edit distance from SequenceMatcher opcodes.

    Args:
      before: The words of one version.
      after: The words of the other.

    Returns:
      The number of words edited over the length of the longer version,
      rounded to 3 decimals: 0 for identical versions, 1 for disjoint ones.
    """
    if not before and not after:
        return 0.0
    matcher = difflib.SequenceMatcher(None, before, after, autojunk=False)
    edits = sum(
        max(i2 - i1, j2 - j1)
        for tag, i1, i2, j1, j2 in matcher.get_opcodes()
        if tag != "equal"
    )
    return round(edits / max(len(before), len(after)), 3)


def word_diff(before: Sequence[str], after: Sequence[str]) -> str:
    """Inline diff in wdiff style: [-deleted-] {+inserted+}."""
    matcher = difflib.SequenceMatcher(None, before, after, autojunk=False)
    out = []
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        old = " ".join(before[i1:i2])
        new = " ".join(after[j1:j2])
        if tag == "equal":
            out.append(old)
        elif tag == "delete":
            out.append("[-%s-]" % old)
        elif tag == "insert":
            out.append("{+%s+}" % new)
        else:
            out.append("[-%s-] {+%s+}" % (old, new))
    return " ".join(out)


def best_match(
    target: Sequence[str], candidates: Sequence[Sequence[str]]
) -> tuple[int, float]:
    """Finds the candidate most similar to target.

    Args:
      target: The words of one paragraph.
      candidates: The words of each paragraph to compare it with.

    Returns:
      A tuple (index, ratio): the index of the best candidate, -1 when no
      candidate is similar at all, and its SequenceMatcher ratio.
    """
    best_index, best_ratio = -1, 0.0
    for index, candidate in enumerate(candidates):
        matcher = difflib.SequenceMatcher(
            None, target, candidate, autojunk=False
        )
        if (
            matcher.real_quick_ratio() < best_ratio
            or matcher.quick_ratio() < best_ratio
        ):
            continue
        ratio = matcher.ratio()
        if ratio > best_ratio:
            best_index, best_ratio = index, ratio
    return best_index, best_ratio


def capture(
    entry: dict[str, Any], repo: pathlib.Path, threshold: float
) -> dict[str, Any]:
    """Pairs each paragraph an entry delivered with its accepted version.

    Args:
      entry: A log entry, as parse_entry() returns it.
      repo: The paper's repository; the entry's file field is relative to it.
      threshold: The smallest match ratio that pairs two paragraphs.

    Returns:
      The entry's "id" and "meta"; a "status", "ok" or why nothing could be
      compared; and under "paragraphs", per delivered paragraph, its words,
      the accepted words (None when no paragraph of the file matches well
      enough), their edit distance and the match ratio.
    """
    file_name = entry.get("file")
    result: dict[str, Any] = {
        "id": entry["id"],
        "meta": entry,
        "paragraphs": [],
        "status": "ok",
    }
    if not file_name:
        result["status"] = "no file: field -- nothing to compare against"
        return result
    target = repo / file_name
    if not target.exists():
        result["status"] = f"file not found: {file_name}"
        return result
    text = target.read_text(encoding="utf-8", errors="replace")
    file_paragraphs = [words(paragraph) for paragraph in paragraphs(text)]
    for output_paragraph in paragraphs(entry["output"]):
        delivered = words(output_paragraph)
        index, ratio = best_match(delivered, file_paragraphs)
        if index == -1 or ratio < threshold:
            result["paragraphs"].append(
                {
                    "delivered": delivered,
                    "accepted": None,
                    "distance": 1.0,
                    "ratio": ratio,
                }
            )
        else:
            accepted = file_paragraphs[index]
            result["paragraphs"].append(
                {
                    "delivered": delivered,
                    "accepted": accepted,
                    "distance": edit_distance(delivered, accepted),
                    "ratio": ratio,
                }
            )
    return result


# ---------------------------------------------------------------------------
# output
# ---------------------------------------------------------------------------


def render(result: dict[str, Any]) -> str:
    """Formats one captured entry as a section of corrections.md."""
    meta = result["meta"]
    slot = meta.get("slot", "?")
    register = meta.get("register", "?")
    version = meta.get("profile_version", "?")
    agent = meta.get("agent", "?")
    head = (
        f"## {result['id']} · {slot} · {register} · profile {version} · {agent}"
    )
    file_name = meta.get("file", "-")
    date = meta.get("date", "-")
    lines = [head, f"file: {file_name} · date: {date}"]
    if result["status"] != "ok":
        lines.append(f"status: {result['status']}")
        return "\n".join(lines) + "\n"
    pairs = result["paragraphs"]
    matched = sum(1 for pair in pairs if pair["accepted"] is not None)
    mean = (
        round(sum(pair["distance"] for pair in pairs) / len(pairs), 3)
        if pairs
        else None
    )
    lines.append(
        f"paragraphs matched: {matched}/{len(pairs)} · mean distance: {mean}"
    )
    if meta.get("note"):
        lines.append(f"note: {meta['note']}")
    for number, pair in enumerate(pairs, 1):
        if pair["accepted"] is None:
            lines.append(
                f"\n### ¶{number} — not found in file (best ratio"
                f" {pair['ratio']:.2f}); replaced or removed, distance 1.0"
            )
            lines.append("delivered: " + " ".join(pair["delivered"]))
        elif pair["distance"] == 0.0:
            lines.append(f"\n### ¶{number} — accepted verbatim")
        else:
            lines.append(f"\n### ¶{number} — distance {pair['distance']}")
            lines.append(word_diff(pair["delivered"], pair["accepted"]))
    return "\n".join(lines) + "\n"


def recurring_tokens(
    results: Sequence[dict[str, Any]], limit: int = 12
) -> tuple[list[tuple[str, int]], list[tuple[str, int]]]:
    """Most frequently deleted / inserted words across all captured edits.

    Args:
      results: The captured entries.
      limit: How many words to list of each kind.

    Returns:
      A tuple (removed, added): the most often removed and the most often
      added words, lowercased and stripped of punctuation, with their counts.
    """
    removed: collections.Counter[str] = collections.Counter()
    added: collections.Counter[str] = collections.Counter()
    for result in results:
        for pair in result["paragraphs"]:
            if pair["accepted"] is None:
                continue
            delivered, accepted = pair["delivered"], pair["accepted"]
            matcher = difflib.SequenceMatcher(
                None, delivered, accepted, autojunk=False
            )
            for tag, i1, i2, j1, j2 in matcher.get_opcodes():
                if tag in ("delete", "replace"):
                    removed.update(
                        word.strip(".,;:()").lower()
                        for word in delivered[i1:i2]
                    )
                if tag in ("insert", "replace"):
                    added.update(
                        word.strip(".,;:()").lower() for word in accepted[j1:j2]
                    )
    return removed.most_common(limit), added.most_common(limit)


def summary(results: Sequence[dict[str, Any]]) -> str:
    """Summarizes the mean edit distance by profile version and by slot.

    Args:
      results: The captured entries.

    Returns:
      The summary, with the most often removed and added words.
    """
    by_slot: collections.defaultdict[str, list[float]] = (
        collections.defaultdict(list)
    )
    by_version: collections.defaultdict[str, list[float]] = (
        collections.defaultdict(list)
    )
    for result in results:
        if result["status"] != "ok" or not result["paragraphs"]:
            continue
        distances = [pair["distance"] for pair in result["paragraphs"]]
        mean = sum(distances) / len(distances)
        by_slot[result["meta"].get("slot", "?")].append(mean)
        by_version[result["meta"].get("profile_version", "?")].append(mean)
    out = ["\nmean edit distance (0 = accepted verbatim, 1 = replaced)"]
    out.append("  by profile version:")
    for version in sorted(by_version):
        means = by_version[version]
        mean = sum(means) / len(means)
        out.append(f"    {version:<10} n={len(means):<3} mean={mean:.3f}")
    out.append("  by slot:")
    for slot in sorted(by_slot):
        means = by_slot[slot]
        mean = sum(means) / len(means)
        out.append(f"    {slot:<14} n={len(means):<3} mean={mean:.3f}")
    removed, added = recurring_tokens(results)
    if removed:
        listed = ", ".join(f"{word}({count})" for word, count in removed)
        out.append("  most often removed: " + listed)
    if added:
        listed = ", ".join(f"{word}({count})" for word, count in added)
        out.append("  most often added:   " + listed)
    return "\n".join(out)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------


def _parse_arguments(argv: Sequence[str] | None) -> argparse.Namespace:
    """Parses the command line."""
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--repo",
        help="repo root (default: nearest ancestor of cwd containing"
        " .co-writer/)",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.5,
        help="min match ratio to pair a delivered paragraph with one in the"
        " file",
    )
    parser.add_argument(
        "--recompute",
        action="store_true",
        help="rebuild corrections.md from scratch",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    """Captures a paper repository's new log entries into corrections.md.

    Args:
      argv: The arguments after the program name; None reads sys.argv.

    Returns:
      The exit status: 2 when there is no session log, 0 otherwise.
    """
    args = _parse_arguments(argv)
    repo: pathlib.Path | None
    if args.repo:
        repo = pathlib.Path(args.repo).expanduser().resolve()
    else:
        repo = find_repo(pathlib.Path.cwd().resolve())
    if repo is None or not (repo / LOG_DIR).is_dir():
        print("no .co-writer/log/ found; nothing to capture", file=sys.stderr)
        return 2

    entries = []
    for path in sorted((repo / LOG_DIR).glob("*.md")):
        entry = parse_entry(path)
        if entry:
            entries.append(entry)
    out_path = repo / OUT_FILE
    existing = ""
    if out_path.exists() and not args.recompute:
        existing = out_path.read_text(encoding="utf-8")
    done = set(re.findall(r"^## (\S+) ·", existing, flags=re.M))

    results = [capture(entry, repo, args.threshold) for entry in entries]
    new = [result for result in results if result["id"] not in done]

    text = existing if existing else _HEADER
    text += "".join(render(result) + "\n" for result in new)
    out_path.write_text(text, encoding="utf-8")

    print(
        f"{len(entries)} log entries, {len(new)} new, written to"
        f" {out_path.relative_to(repo)}"
    )
    for result in new:
        if result["status"] != "ok":
            print(f"  {result['id']}: {result['status']}")
    print(summary(results))
    return 0


if __name__ == "__main__":
    sys.exit(main())
